import { promises as fs } from "node:fs";

export type EnvMap = Record<string, string>;

// Minimal dotenv parser: handles KEY=value, # comments, blank lines,
// and double-quoted values. Anything more exotic isn't needed for our
// own .env files.
export function parseEnv(text: string): EnvMap {
  const out: EnvMap = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

export function serializeEnv(
  values: EnvMap,
  order: string[],
  comments: Record<string, string> = {}
): string {
  const lines: string[] = [
    "# Generated by `withvibe`. Edit secrets carefully — rotating",
    "# INTERNAL_JWT_SECRET invalidates every active session.",
    "",
  ];
  const seen = new Set<string>();
  for (const key of order) {
    if (!(key in values)) continue;
    if (comments[key]) lines.push(`# ${comments[key]}`);
    lines.push(`${key}=${quoteIfNeeded(values[key]!)}`);
    lines.push("");
    seen.add(key);
  }
  for (const key of Object.keys(values)) {
    if (seen.has(key)) continue;
    lines.push(`${key}=${quoteIfNeeded(values[key]!)}`);
  }
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function quoteIfNeeded(v: string): string {
  if (v === "") return "";
  if (/[\s"'#$`\\]/.test(v)) {
    return `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return v;
}

export async function writeEnvFile(
  filePath: string,
  text: string
): Promise<void> {
  // Restrictive perms: secrets live here.
  await fs.writeFile(filePath, text, { mode: 0o600 });
}

export async function readEnvFile(filePath: string): Promise<EnvMap> {
  const text = await fs.readFile(filePath, "utf8").catch(() => "");
  return parseEnv(text);
}
