import { promises as fs } from "node:fs";
import path from "node:path";
import chalk from "chalk";
import ora from "ora";
import prompts from "prompts";
import {
  fetchExportReadiness,
  fetchLocalBundle,
  type ExportReadinessResponse,
  type LocalBundleResponse,
} from "./api.js";
import { loadConfig, withvibeHome } from "./config.js";
import { run } from "./exec.js";
import { confirmGitHubAccount } from "./git-auth.js";
import { pickFreePorts } from "./ports.js";
import { runPreflight } from "./preflight.js";

// Same ${VAR} form the server uses in template compose files.
const INTERPOLATION_RE = /\$\{([A-Z][A-Z0-9_]*)\}/g;

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "env"
  );
}

function interpolate(body: string, vars: Record<string, string>): string {
  return body.replace(INTERPOLATION_RE, (match, key: string) => {
    return key in vars ? vars[key] : match;
  });
}

function renderDotEnv(vars: Record<string, string>): string {
  const lines = ["# Generated by withvibe CLI — edit with care."];
  for (const [k, v] of Object.entries(vars)) {
    const escaped = v
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r");
    lines.push(`${k}="${escaped}"`);
  }
  return lines.join("\n") + "\n";
}

export async function envCommand(
  envId: string,
  opts: { open: boolean; force: boolean }
) {
  const cfg = await loadConfig();
  if (!cfg) {
    console.error(
      chalk.red("Not logged in."),
      "Run `withvibe login` first."
    );
    process.exit(1);
  }

  console.log(chalk.bold("\n▸ Preflight"));
  const { haveCode, macAppPath } = await runPreflight({ autoInstall: true });

  console.log(chalk.bold("\n▸ GitHub authentication"));
  await confirmGitHubAccount();

  console.log(chalk.bold("\n▸ Checking export readiness"));
  await checkExportReadiness(cfg.server, cfg.token, envId, opts.force);

  console.log(chalk.bold("\n▸ Fetching env bundle"));
  const spinner = ora("Contacting server…").start();
  let bundle: LocalBundleResponse;
  try {
    bundle = await fetchLocalBundle(cfg.server, cfg.token, envId);
    spinner.succeed(`Loaded "${bundle.env.title}" (${bundle.repos.length} repo${bundle.repos.length === 1 ? "" : "s"})`);
  } catch (err) {
    spinner.fail("Failed to fetch bundle");
    console.error(chalk.red(String(err)));
    process.exit(1);
  }

  const envDir = path.join(
    withvibeHome(),
    bundle.env.workspaceId,
    `${slugify(bundle.env.title)}-${bundle.env.id.slice(-6)}`
  );
  // Repos live as siblings of docker-compose.yml, matching the hosted
  // layout (<envDir>/<repoName>/). Compose files reference repos as
  // `./repo-name`, so any other layout would break volume mounts.
  await fs.mkdir(envDir, { recursive: true });
  console.log(chalk.dim(`  → ${envDir}`));

  await cloneAllRepos(bundle.repos, envDir);
  await writeBundleFiles(envDir, bundle);
  await dockerComposeUp(envDir);
  await printServicePorts(envDir);
  const workspacePath = await writeCodeWorkspace(envDir, bundle);

  if (opts.open && haveCode) {
    console.log(chalk.bold("\n▸ Opening VSCode"));
    await openEditor(workspacePath, macAppPath).catch(() => {
      console.log(
        chalk.yellow("  (failed to launch VSCode — open this file manually:"),
        workspacePath,
        chalk.yellow(")")
      );
    });
  } else if (!haveCode) {
    console.log(
      chalk.yellow("\nVSCode CLI not available — open this file manually:"),
      workspacePath
    );
  }

  console.log(chalk.green("\n✓ Env ready."), chalk.dim(envDir));
}

type ComposePsRow = {
  Service?: string;
  Name?: string;
  State?: string;
  Publishers?:
    | {
        URL?: string;
        TargetPort?: number;
        PublishedPort?: number;
        Protocol?: string;
      }[]
    | null;
};

async function printServicePorts(envDir: string): Promise<void> {
  const res = await run(
    "docker",
    ["compose", "ps", "--format", "json"],
    { cwd: envDir, streamTo: "pipe" }
  );
  if (res.code !== 0) return;

  // `docker compose ps --format json` emits either a JSON array or NDJSON
  // depending on the CLI version. Handle both.
  const text = res.stdout.trim();
  if (!text) return;
  const rows: ComposePsRow[] = [];
  if (text.startsWith("[")) {
    try {
      rows.push(...(JSON.parse(text) as ComposePsRow[]));
    } catch {
      return;
    }
  } else {
    for (const line of text.split("\n")) {
      const s = line.trim();
      if (!s) continue;
      try {
        rows.push(JSON.parse(s) as ComposePsRow);
      } catch {
        // skip malformed line
      }
    }
  }

  // Group published ports by service. A single container may publish
  // multiple host ports (e.g. postgres + metrics), so we keep them all.
  const byService = new Map<string, { host: number; container: number }[]>();
  for (const r of rows) {
    const svc = r.Service || r.Name;
    if (!svc) continue;
    const entries: { host: number; container: number }[] = [];
    for (const p of r.Publishers ?? []) {
      if (!p || !p.PublishedPort || !p.TargetPort) continue;
      entries.push({ host: p.PublishedPort, container: p.TargetPort });
    }
    if (entries.length === 0) continue;
    const existing = byService.get(svc) ?? [];
    existing.push(...entries);
    byService.set(svc, existing);
  }

  if (byService.size === 0) {
    console.log(chalk.dim("\n  (No services published any ports to the host.)"));
    return;
  }

  console.log(chalk.bold("\n▸ Services"));
  for (const [svc, ports] of byService) {
    // Dedupe (host, container) pairs in case compose reports them twice
    // for different protocols (tcp + udp) with the same port number.
    const seen = new Set<string>();
    const uniq = ports.filter((p) => {
      const k = `${p.host}-${p.container}`;
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    });
    const parts = uniq.map(
      (p) =>
        `${chalk.cyan(`http://localhost:${p.host}`)} ${chalk.dim(
          `→ container :${p.container}`
        )}`
    );
    console.log(`  ${chalk.bold(svc)}  ${parts.join("  ")}`);
  }
}

async function openEditor(
  workspacePath: string,
  macAppPath: string | null
): Promise<void> {
  // Prefer the `code` CLI shim when it exists — opens in the current window
  // and honors the .code-workspace format natively.
  const codeOnPath = await run("which", ["code"]).catch(
    () => ({ code: 1 } as { code: number })
  );
  if (codeOnPath.code === 0) {
    await run("code", [workspacePath], { streamTo: "inherit" });
    return;
  }
  // macOS fallback: launch via `open -a` against the .app bundle.
  if (process.platform === "darwin" && macAppPath) {
    await run("open", ["-a", macAppPath, workspacePath], {
      streamTo: "inherit",
    });
    return;
  }
  throw new Error("No way to launch editor");
}

async function checkExportReadiness(
  server: string,
  token: string,
  envId: string,
  force: boolean
): Promise<void> {
  const spinner = ora("Inspecting server-side env clones…").start();
  let readiness: ExportReadinessResponse;
  try {
    readiness = await fetchExportReadiness(server, token, envId);
  } catch (err) {
    spinner.fail("Failed to check export readiness");
    console.error(chalk.red(String(err)));
    process.exit(1);
  }

  if (readiness.ready) {
    spinner.succeed("All env repos are committed and pushed");
    return;
  }

  spinner.warn("Some env repos have changes that won't be exported");

  for (const r of readiness.repos) {
    if (r.error) {
      console.log(
        chalk.yellow(`  • ${r.name}: ${r.error}`)
      );
      continue;
    }
    if (r.uncommitted === 0 && r.unpushed === 0) continue;
    const parts: string[] = [];
    if (r.uncommitted > 0) parts.push(`${r.uncommitted} uncommitted file(s)`);
    if (r.unpushed > 0) parts.push(`${r.unpushed} unpushed commit(s)`);
    console.log(
      chalk.yellow(`  • ${r.name} (${r.branch}): ${parts.join(", ")}`)
    );
  }

  console.log(
    chalk.yellow(
      "\nThe local clone pulls from GitHub. Anything not committed and pushed\non the env's branch will NOT appear in your local checkout."
    )
  );
  console.log(
    chalk.dim(
      "→ Open the env in the web app, commit & push the changes, then re-run this command."
    )
  );

  if (force) {
    console.log(chalk.dim("\n--force given, continuing anyway."));
    return;
  }

  const { proceed } = await prompts({
    type: "confirm",
    name: "proceed",
    message: "Continue export anyway?",
    initial: false,
  });
  if (!proceed) {
    console.log(chalk.dim("Aborted."));
    process.exit(0);
  }
}

async function cloneAllRepos(
  repos: LocalBundleResponse["repos"],
  envDir: string
) {
  console.log(chalk.bold("\n▸ Cloning repositories"));
  for (const repo of repos) {
    const target = path.join(envDir, repo.name);
    const exists = await fs
      .stat(target)
      .then((s) => s.isDirectory())
      .catch(() => false);
    if (exists) {
      console.log(chalk.dim(`  skip ${repo.name} (already cloned)`));
      continue;
    }
    const spinner = ora(`Cloning ${repo.name} (${repo.branch})…`).start();
    const res = await run(
      "git",
      [
        "clone",
        "--branch",
        repo.branch,
        "--single-branch",
        repo.url,
        target,
      ],
      { streamTo: "pipe" }
    );
    if (res.code !== 0) {
      spinner.fail(`git clone ${repo.name} failed`);
      console.error(res.stderr);
      if (
        /Repository not found/i.test(res.stderr) ||
        /Permission denied/i.test(res.stderr) ||
        /Authentication failed/i.test(res.stderr)
      ) {
        console.error(
          chalk.yellow(
            "\nThis usually means your active GitHub account doesn't have access to this repo.\nTry `gh auth switch` (or `gh auth login`) to pick an account with access, then re-run."
          )
        );
      }
      process.exit(1);
    }
    spinner.succeed(`Cloned ${repo.name}`);
  }
}

async function writeBundleFiles(
  envDir: string,
  bundle: LocalBundleResponse
): Promise<void> {
  if (bundle.bundle.kind === "none") {
    console.log(
      chalk.yellow("\n(No compose file for this env — skipping docker setup.)")
    );
    return;
  }

  console.log(chalk.bold("\n▸ Writing compose files"));

  if (bundle.bundle.kind === "custom") {
    await fs.writeFile(
      path.join(envDir, "docker-compose.yml"),
      bundle.bundle.composeFile,
      "utf-8"
    );
    console.log(chalk.dim("  → docker-compose.yml (custom)"));
    return;
  }

  // Template path: allocate host ports, write .env, materialize assets.
  const t = bundle.bundle;
  const ports = await pickFreePorts(t.portKeys.length);
  const portVars: Record<string, string> = {};
  t.portKeys.forEach((key, i) => {
    portVars[key] = String(ports[i]);
  });
  const allVars = { ...t.resolvedVars, ...portVars };

  await fs.writeFile(
    path.join(envDir, "docker-compose.yml"),
    t.composeFile,
    "utf-8"
  );
  await fs.writeFile(
    path.join(envDir, ".env"),
    renderDotEnv(allVars),
    "utf-8"
  );
  console.log(chalk.dim("  → docker-compose.yml"));
  console.log(chalk.dim("  → .env"));

  for (const asset of t.assets) {
    const target = path.join(envDir, asset.path);
    const resolved = path.resolve(target);
    if (!resolved.startsWith(path.resolve(envDir) + path.sep)) {
      throw new Error(`Asset path escapes env dir: ${asset.path}`);
    }
    await fs.mkdir(path.dirname(resolved), { recursive: true });
    const content = asset.isTemplate
      ? interpolate(asset.content, allVars)
      : asset.content;
    await fs.writeFile(resolved, content, "utf-8");
    console.log(chalk.dim(`  → ${asset.path}`));
  }

  if (t.portKeys.length > 0) {
    console.log(chalk.dim("  allocated host ports:"));
    for (const k of t.portKeys) {
      console.log(chalk.dim(`    ${k}=${portVars[k]}`));
    }
  }
}

async function dockerComposeUp(envDir: string): Promise<void> {
  // Skip if there's no compose file at all (bundle.kind === "none" path).
  const hasCompose = await fs
    .stat(path.join(envDir, "docker-compose.yml"))
    .then(() => true)
    .catch(() => false);
  if (!hasCompose) return;

  console.log(chalk.bold("\n▸ Starting docker compose (this may take a while on first run)"));
  const res = await run("docker", ["compose", "up", "-d", "--build"], {
    cwd: envDir,
    streamTo: "inherit",
  });
  if (res.code !== 0) {
    console.error(chalk.red(`docker compose exited with code ${res.code}`));
    process.exit(1);
  }
}

async function writeCodeWorkspace(
  envDir: string,
  bundle: LocalBundleResponse
): Promise<string> {
  const folders: { name: string; path: string }[] = [
    { name: "env-root", path: "." },
    ...bundle.repos.map((r) => ({
      name: r.name,
      path: `./${r.name}`,
    })),
  ];
  const workspace = {
    folders,
    settings: {
      "files.exclude": { "**/.DS_Store": true },
    },
  };
  const filePath = path.join(envDir, `${bundle.env.title}.code-workspace`);
  await fs.writeFile(filePath, JSON.stringify(workspace, null, 2), "utf-8");
  return filePath;
}
